In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
dataset = pd.read_csv('student.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [5]:
print(X)

[[6.83 1.   0.  ]
 [6.56 2.   0.  ]
 [4.3  2.   0.  ]
 [5.67 4.   0.  ]
 [8.67 2.   0.  ]
 [7.55 3.   0.  ]
 [6.67 2.   0.  ]
 [8.99 1.   0.  ]
 [5.19 4.   1.  ]
 [6.75 3.   0.  ]
 [6.59 2.   1.  ]
 [8.56 3.   0.  ]
 [7.75 2.   0.  ]
 [7.9  1.   1.  ]
 [8.19 1.   0.  ]
 [6.55 2.   1.  ]
 [6.36 3.   0.  ]
 [8.44 2.   0.  ]
 [8.41 1.   0.  ]
 [7.67 2.   0.  ]
 [7.42 2.   0.  ]
 [8.16 2.   0.  ]
 [5.05 4.   1.  ]
 [5.85 2.   0.  ]
 [5.45 3.   1.  ]
 [7.96 1.   0.  ]
 [6.51 2.   0.  ]
 [6.73 2.   0.  ]
 [5.94 4.   0.  ]
 [7.48 2.   0.  ]
 [8.13 3.   1.  ]
 [6.67 3.   0.  ]
 [5.4  5.   0.  ]
 [8.78 2.   1.  ]
 [8.72 2.   0.  ]
 [7.1  1.   0.  ]
 [7.86 2.   0.  ]
 [7.19 4.   1.  ]
 [5.62 4.   0.  ]
 [7.88 2.   0.  ]
 [5.28 3.   1.  ]
 [8.92 2.   0.  ]
 [5.46 3.   1.  ]
 [8.3  2.   0.  ]
 [8.09 1.   0.  ]
 [6.18 2.   0.  ]
 [7.01 3.   0.  ]
 [5.01 1.   0.  ]
 [5.54 3.   0.  ]
 [5.09 1.   0.  ]
 [5.09 2.   0.  ]
 [7.31 1.   0.  ]
 [8.71 3.   0.  ]
 [5.52 1.   0.  ]
 [8.76 3.   0.  ]
 [8.69 2. 

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state = 0)

In [7]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [8]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[7.82 7.75]
 [6.53 6.62]
 [6.78 6.83]
 [8.04 7.87]
 [6.84 6.87]
 [7.91 8.2 ]
 [7.58 7.62]
 [7.66 7.78]
 [7.62 7.45]
 [7.7  7.67]
 [7.47 7.44]
 [7.99 8.1 ]
 [7.32 7.22]
 [7.27 7.35]
 [7.88 7.9 ]
 [8.04 8.05]
 [7.88 7.94]
 [6.78 6.82]
 [7.37 7.32]
 [7.41 7.26]]


In [9]:
import joblib
joblib.dump(regressor, "cgpa_predictor.pkl")

['cgpa_predictor.pkl']

In [10]:
model = joblib.load("cgpa_predictor.pkl")

In [11]:
print(X_test)

[[8.41 1.   0.  ]
 [5.19 2.   1.  ]
 [5.72 3.   1.  ]
 [8.88 2.   0.  ]
 [5.79 1.   0.  ]
 [8.66 1.   0.  ]
 [7.55 3.   0.  ]
 [7.99 1.   0.  ]
 [7.75 2.   0.  ]
 [8.08 1.   0.  ]
 [7.26 3.   0.  ]
 [8.75 2.   0.  ]
 [6.97 2.   0.  ]
 [6.93 1.   0.  ]
 [8.34 3.   0.  ]
 [8.99 1.   0.  ]
 [8.78 2.   1.  ]
 [5.64 1.   0.  ]
 [7.19 4.   1.  ]
 [7.31 1.   0.  ]]


In [12]:
model.predict([[9.08,1,1]])

array([7.95])

In [13]:
model.predict([[1.08,1,1]])

array([4.95])